### ISSUE TITLE
Low Priority: Reduce vertical space between images on Explore/Ecological Communities page

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#14]
Low priority
Reduce vertical space between the images in the right-hand column on the Explore/Ecological Communities page

Current:
<img width="839" alt="ecological values images current" src="https://github.com/user-attachments/assets/0c1e0bbb-d8a0-4bab-bc31-9a99e6092130">

Update:
<img width="554" alt="ecological values images" src="https://github.com/user-attachments/assets/b114909e-048a-4878-8e86-1ff8dc4b4f3d">

**Comment by jobara** [comment]
@dayotte each image is grouped with content on the left. In some cases there maybe multiple paragraphs of text. https://github.com/IMERSS/xetthecum-storymap/blob/87633272888368b6f1b8e300a8d8528917da80f3/ecological-values.qmd#L12-L22 Because the text and related image are in sort of a row together I can't equally space out all the images. I could make the images start from the top of the related text though if that's sufficient. 

If the images aren't really specific to the content and you just want them all together we could reorganize the content of the page and change up the styling.

**Comment by dayotte** [comment]
The images are not specific to the sections of content, and I think they'd look better all together in a column (like in the mockup). When you say reorganize the content and restyle, is that what you mean, or something else?

**Comment by jobara** [comment]
> The images are not specific to the sections of content, and I think they'd look better all together in a column (like in the mockup). When you say reorganize the content and restyle, is that what you mean, or something else?

Yes that's what I mean, and they'd probably appear grouped together towards the top of the page.
